"""
Django settings for ifteca_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from django.template import context as _dj_context

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(value, default):
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-a!5jud18&opsed^@jp$gc&pyrwwcz2t2r*+=$+qdc+$x4a+ibw')
DEBUG = _env_bool(os.getenv('DJANGO_DEBUG'), True)

_allowed_hosts_raw = os.getenv('DJANGO_ALLOWED_HOSTS')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()] if _allowed_hosts_raw else ['localhost', '127.0.0.1', '0.0.0.0']


# --------------------------
# A P P S
# --------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'livereload',

    # REST
    'rest_framework',
    'rest_framework.authtoken',

    # Suas apps
    'salas',
    'reservas',
    'auth_app',  
]


# --------------------------
# M I D D L E W A R E
# --------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Injeta o script de LiveReload apenas em modo dev
    'livereload.middleware.LiveReloadScript',
]


ROOT_URLCONF = 'ifteca_project.urls'


# --------------------------
# TEMPLATES
# --------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ifteca_project.wsgi.application'


# --------------------------
# DATABASE
# --------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Database in repo-root/data/
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


# --------------------------
# AUTH PASSWORD VALIDATION
# --------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------
# REST FRAMEWORK CONFIG
# --------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# --------------------------
# TIME / LANGUAGE
# --------------------------
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# --------------------------
# STATIC FILES
# --------------------------
STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirecionamento de login para a tela personalizada
LOGIN_URL = '/login/'


# --------------------------
# LOGIN POR E-MAIL (opcional)
# --------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# --------------------------
# LOGGING BÁSICO PARA DEBUG
# --------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # habilita INFO e acima para app reservas
        'reservas': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ------------------------------------------------------------------
# Workaround para bug do Django 5.1 em Python 3.14 com copy(Context)
# ------------------------------------------------------------------
def _safe_basecontext_copy(self):
    duplicate = self.__class__(self.dicts[0] if self.dicts else {})
    duplicate.dicts = self.dicts[:]
    return duplicate

_dj_context.BaseContext.__copy__ = _safe_basecontext_copy
