# Generated by Django 5.1.3 on 2025-11-27 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_add_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
