# Generated by Django 5.1.3 on 2025-12-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_remove_individual_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se a sala está ativa no sistema. Salas inativas não aparecem para usuários.', verbose_name='Ativo'),
        ),
    ]
