# Generated by Django 5.1.3 on 2025-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_sala_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('nome',), name='unique_nome_sala_ativa'),
        ),
    ]
