# Generated by Django 5.2.8 on 2025-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala')),
                ('capacidade', models.PositiveIntegerField(default=1, verbose_name='Capacidade Máxima')),
                ('tipo', models.CharField(choices=[('ESTUDO_INDIVIDUAL', 'Estudo Individual'), ('ESTUDO_GRUPO', 'Estudo em Grupo'), ('LABORATORIO', 'Laboratório'), ('SALA_AULA', 'Sala de Aula')], default='ESTUDO_GRUPO', max_length=30, verbose_name='Tipo de Sala')),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização (Bloco/Andar)')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
    ]
