# Generated by Django 5.1.3 on 2025-12-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_unify_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
    ]
