# Generated by Django 5.1.3 on 2025-12-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_cancelada'),
        ('salas', '0009_alter_sala_nome_sala_unique_nome_sala_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='salas.sala'),
        ),
    ]
